# Generated by Django 5.1.6 on 2025-04-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250, verbose_name='')),
                ('password', models.CharField(max_length=250)),
                ('graduation_year', models.IntegerField(max_length=4)),
                ('profile_picture', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
