# Generated by Django 5.1.1 on 2025-06-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Announcements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='user',
        ),
    ]
