# Generated by Django 5.1.6 on 2025-04-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('club_members', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('room_number', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('email', models.EmailField(max_length=250, verbose_name='')),
            ],
        ),
    ]
